controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
recipe_comment:
    path: /recipe/{id}/comment
    controller: App\Controller\CommentController::addComment
    methods: POST